### ISSUE TITLE
generator params：shape range=(3, 8), coverage range=(0.2, 0.5)

### ISSUE THREAD

**Issue by WY0320914** [theilem/uavSim#14]
Still don't quite understand what they mean. What I understand is that;
 1.Shape range=(3,8) refers to the number of random target shapes that can be generated? Like generate 4 random target areas or 5 etc?
2. Does coverage range=(0.2,0.5) mean that the sum of all generated target areas is 20% to 50% of the entire map? If so, if the free area accounts for 80% of the entire map, does it require setting the coverage range value to 0.8 to use all the free area as the coverage target area?

**Comment by theilem** [comment]
1. Yes
2. The coverage range defines the range of accepted range of target area ratios compared to all cells. If, after generation, the generated area does not fall within that range, a new target zone is generated. If you want to set the entire free area as a target, I would recommend writing a quick function that does not use random shapes.
