### ISSUE TITLE
POMDP

### ISSUE THREAD

**Issue by WY0320914** [theilem/uavSim#15]
Is the Partially Observable Markov Decision Process mentioned in the article caused by the global-local map scheme? What does it mean to be partially observable?

**Comment by theilem** [comment]
Yes it is. Since the local map is only a smaller local view of the total map and the global map is a compressed view, the agent does not see everything in exact detail. That means that it needs to estimate the exact content of distant cells.

**Comment by WY0320914** [comment]
OK
