### ISSUE TITLE
Resolution changed to 64X64

### ISSUE THREAD

**Issue by WY0320914** [theilem/uavSim#19]
In the CPP problem, after only modifying the environment map to a resolution of 64X64, the generated coverage results are not good. Why is this? Do you need to modify the original parameters of the program?
The generated cpp results do not cover as much of the target area as possible.

![64结果图](https://github.com/user-attachments/assets/7c8d169a-d06b-4e75-a021-24885378fa5d)

**Comment by theilem** [comment]
It seems like the power budget is not enough. You should increase the movement budget range

**Comment by WY0320914** [comment]
> It seems like the power budget is not enough. You should increase the movement budget range

The power setting is sufficient, but the coverage is only 20%. When inputting a 64X64 map, do you need to modify some hyperparameters or increase the number of training steps?
![7808802978ca4cac61a0956e83547c5](https://github.com/user-attachments/assets/135a4de5-cffa-4dd5-8015-ae9a2a4c75cb)

**Comment by theilem** [comment]
Probably you will need to adapt some parameters like the local map size, global map scaling, training steps. I would in any case highly recommend to use the latest code as it outperforms the previous one.
