### ISSUE TITLE
Program operation error

### ISSUE THREAD

**Issue by lingyun888** [theilem/uavSim#2]
Hello, an error occurs when the program is running. The error is as follows:  tensorflow.python.framework.errors_impl.InternalError: dnn PoolForward launch failed [Op:AvgPool]

**Comment by theilem** [comment]
Which version of tensorflow and tensorflow-gpu do you use?

**Comment by lingyun888** [comment]
tensorflow==2.3.0

**Comment by theilem** [comment]
Try upgrading your tensorflow to 2.6 or greater.
