### ISSUE TITLE
High is out of bounds for int32

### ISSUE THREAD

**Issue by BazilaAfridi** [theilem/uavSim#3]
![image](https://user-images.githubusercontent.com/69035494/150680593-256a1e6a-3970-4ccb-8308-48e8f57c5af7.png)

Can anyone help me please to find out why I'm having this error "High is out of bounds for int32"

**Comment by theilem** [comment]
Try reducing the value in __generate_random_shapes from (2**32 - 1) to (2**31 - 1) or reduce it even further.

**Comment by BazilaAfridi** [comment]
Yes was able to solve the issue by reducing 32 to 31. Thank you so much sir.
