### ISSUE TITLE
How to continue training using the saved weights?

### ISSUE THREAD

**Issue by BazilaAfridi** [theilem/uavSim#4]
I have started my training with following cmd:
python main.py --cpp --gpu --config config/manhattan32_cpp.json --id manhattan32_cpp

I wanted to know what should I do if my PC turned off during training? How can I continue my training using the saved weights? As the latest weights are storing in the models folder like below image. 
![image](https://user-images.githubusercontent.com/69035494/150970867-78cf57ff-1ba4-4fc2-9d60-2862eb325aa5.png)

Should I add weights in the above command like below to start the training with the saved weights like below?
python main.py --cpp --weights models/manhattan32_cpp_best --gpu --config config/manhattan32_cpp.json --id manhattan32_cpp

If no then can you tell me how I continue my training? and will it start from the 1 iteration or continue from the latest iteration?

**Comment by theilem** [comment]
Actually, this is not implemented. The reason is that the weights are not enough to continue training. The state of the replay memory and the optimizer would also be necessary but we are not saving them. We would also need to save everything else that is keeping track of the training.

**Comment by BazilaAfridi** [comment]
OK Sir thanks for your quick response. I also wanted to know that after training will the UAV agent be able to traverse in unknown png environment successfully?

**Comment by theilem** [comment]
The updated version can partially generalize and the agents can be visualized.
