### ISSUE TITLE
How to draw Manhattan32 picture and what software is used to generate it?

### ISSUE THREAD

**Issue by WY0320914** [theilem/uavSim#6]
How to generate the same M32 and Urban50 images as in this project

**Comment by WY0320914** [comment]
What are the cell dimensions? How is it set? For example, Manhattan32 has 32X32 cells.

**Comment by theilem** [comment]
Those are simple png images with size equal to the map size. Landing zones are blue (0, 255, 0), high obstacles yellow (255, 0, 255), low obstacles green (0, 0, 255), and no-fly zones red (255, 0, 0).
