### ISSUE TITLE
moving_average_length : 200

### ISSUE THREAD

**Issue by WY0320914** [theilem/uavSim#9]
"moving_average_length": 200,   What does the moving average length "200" mean? Is it the moving distance of the UAV? Doesn't UAV move one cell in one step? How long is a cell distance?

**Comment by theilem** [comment]
Where did you find that value? It is usually used for filtering of data for example in the logger.

**Comment by WY0320914** [comment]
"model_stats_params": {
        "save_model": "models/manhattan32_cpp",
        "moving_average_length": 200
In the manhattan 32 cpp.json file in config, the average moving length is 200. What does this mean?

**Comment by WY0320914** [comment]
> Where did you find that value? It is usually used for filtering of data for example in the logger.

"model_stats_params": {
        "save_model": "models/manhattan32_cpp",
        "moving_average_length": 200
In the manhattan 32 cpp.json file in config, the average moving length is 200. What does this mean?

**Comment by theilem** [comment]
It means that during training the last 200 results are stored and averaged for displaying statistics in tensorboard.
